import { Assets } from 'react-native-ui-lib';

Assets.loadAssetsGroup('icons', {
  airplay: require('../assets/icons/airplay.png'),
  album: require('../assets/icons/album.png'),
  arrow_back: require('../assets/icons/arrow_back.png'),
  aspect_ratio: require('../assets/icons/aspect_ratio.png'),
  bar_chart: require('../assets/icons/bar_chart.png'),
  equalizer: require('../assets/icons/equalizer.png'),
  error_outline: require('../assets/icons/error_outline.png'),
  favorite: require('../assets/icons/favorite.png'),
  headset: require('../assets/icons/headset.png'),
  highlight_off: require('../assets/icons/highlight_off.png'),
  keyboard_arrow_down: require('../assets/icons/keyboard_arrow_down.png'),
  keyboard_arrow_right: require('../assets/icons/keyboard_arrow_right.png'),
  library_music: require('../assets/icons/library_music.png'),
  loop: require('../assets/icons/loop.png'),
  movie: require('../assets/icons/movie.png'),
  music_video: require('../assets/icons/music_video.png'),
  notification_important: require('../assets/icons/notification_important.png'),
  pen: require('../assets/icons/pen.png'),
  playlist_add: require('../assets/icons/playlist_add.png'),
  queue_music: require('../assets/icons/queue_music.png'),
  recent_actors: require('../assets/icons/recent_actors.png'),
  restore: require('../assets/icons/restore.png'),
  save_alt: require('../assets/icons/save_alt.png'),
  search: require('../assets/icons/search.png'),
  settings: require('../assets/icons/settings.png'),
  share: require('../assets/icons/share.png'),
  shuffle: require('../assets/icons/shuffle.png'),
  skip_next: require('../assets/icons/skip_next.png'),
  skip_previous: require('../assets/icons/skip_previous.png'),
  text_fields: require('../assets/icons/text_fields.png'),
  thumb_down: require('../assets/icons/thumb_down.png'),
  thumb_up: require('../assets/icons/thumb_up.png'),
  vertical_align_bottom: require('../assets/icons/vertical_align_bottom.png'),
  vertical_align_top: require('../assets/icons/vertical_align_top.png'),
  video_library: require('../assets/icons/video_library.png'),
  email: require('../assets/icons/email.png'),
  password_signin: require('../assets/icons/password_signin.png'),
  eye: require('../assets/icons/eye.png'),
  icon_name: require('../assets/icons/icon_name.png'),
  iconPhone: require('../assets/icons/iconPhone.png'),
  iconTabAccount: require('../assets/icons/iconTabAccount.png'),
  iconTabExplore: require('../assets/icons/iconTabExplore.png'),
  iconTabHome: require('../assets/icons/iconTabHome.png'),
  iconTabRadio: require('../assets/icons/iconTabRadio.png'),
  more_horiz: require('../assets/icons/more_horiz.png'),

  google_plus: require('../assets/images/google-plus.png'),
  facebook: require('../assets/images/facebook.png'),
  twitter: require('../assets/images/twitter.png'),
});

Assets.loadAssetsGroup('background', {
  bgThroughwalk: require('../assets/images/bgThroughwalk.png'),
  brSignIn: require('../assets/images/brSignIn.png'),
  background: require('../assets/images/background.jpg'),
  bgItemSong: require('../assets/images/bgItemSong.png'),
});

Assets.loadAssetsGroup('slideSong', {
  slideSong1: require('../assets/images/slideSong1.png'),
  slideSong2: require('../assets/images/slideSong2.png'),
  slideSong3: require('../assets/images/slideSong3.png'),
  slideSong4: require('../assets/images/slideSong4.png'),
});
